[package]
name = "backdrop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
tokio = { version = "1.25.0", features = ["sync", "rt", "full"], optional = true}

[features]
std = []
default = ["std", "tokio"]